# This is a sample configuration file for the Aye-aye Sleep Monitoring Sensor
# Node.  Use this as a basis for configuring the Raspberry Pi for the specific
# deployment environment.

# Device UUID
# 
# This is the UUID that uniquely identifies this device and configuration.
# Nominally, this will be assigned to the device prior to deployment.  This
# should be unique to the device and deployment - that is, if you move a device,
# assign it a new UUID.  This is to keep the device tree identifiable.
uuid: 12345678-abcd-1234-abcd-123456789abc

# Device Type
# 
# This is the device type.  Use this field to configure the behavior of the
# device.  See the available options in SensorNode.sensor_nodes.
type: ''

# Data Server
# 
# This is the location of the data server.  This can either be a domain name
# such as e4e-asm.ucsd.edu, or an IP address such as 192.168.1.77
data_server: 127.0.0.1

# Data Server Port
# 
# This is the primary port for the data server.  Refer to the data server
# configuration.
port: 9000

# Data Server UUID
# 
# This is the UUID of the data server.  This is used to ensure that data is
# routed correctly on the data server.  Refer to the data server configuration
# for options.
data_server_uuid: 00000000-0000-0000-0000-000000000000

# Sensor Node Heartbeat
# 
# This is how often the heartbeat packet is sent in seconds.
heartbeat_period_s: 60

# IP Camera Configuation Block
# 
# Include this block to configure the IP Camera.  type should be 'IP_Camera'
# IP_CAMERA:
  # IP Camera IP Address - this is the IP Camera's IP address.
  # address: '192.168.1.0'

  # RTSP port - this is the RTSP port for the IP Camera.
  # port: 554

  # IP Camera username - This is the username to access the IP camera's RTSP
  # stream
  # user: username

  # IP camera password - This is the password to access the IP camera's RTSP
  # stream
  # password: password

# Aye-Aye Sleep Monitoring Nesting Box
#
# Include this block to configure the Aye-Aye on Box Unit.  type should be 
# 'ASM_NestingBox'
# ASM_NESTING_BOX:
  # Device Endpoint - video device
  # video_endpoint: /dev/video0

  # Illumination Start Time - start time of illumination for each day in HH:MM
  # illumination_on: '18:00'

  # Illumination Stop Time - stop time of illumination for each day in HH:MM
  # illumination_off: '08:00'

  # Illumination level - percentage of max illumination
  # illumination_level: 50

  # Illumination handle - GPIO pin
  # illumination_pin: 19

# Aye-Aye Animal Flipper
#
# Include this block to configure the animal flipper.  Type should be 
# 'ASM_AnimalFlipper'
# ASM_AnimalFlipper:
  # This is the stepper motor number.  Select from 1 or 2
  # motor: 2

  # This is the total number of steps in one revolution of the motor.
  # motor_steps: 200

  # This is the desired speed of the motor in rpm.
  # motor_speed: 10

  # This is the home direction.  This is assumed to be "in".  Select from 1 or 2
  # home_direction: 1

  # This is the amount of time to remain in the in position
  # in_time_s: 300

  # This is the number of steps to count going in.
  # in_steps: 75

  # This is amount of time to remain in the out position
  # out_time_s: 300

  # This is the number of steps to count going out.
  # out_steps: 75

  # This is the output file to write to
  # data_file: /home/pi/flipper.txt
